# Generated by Django 4.2.13 on 2026-04-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("warehouse_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "warehouses",
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="warehouses_is_acti_178fdd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.IntegerField(db_index=True)),
                (
                    "variant_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("quantity_on_hand", models.IntegerField(default=0)),
                ("reorder_threshold", models.IntegerField(default=10)),
                ("version", models.IntegerField(default=0)),
                (
                    "warehouse",
                    models.ForeignKey(
                        db_column="warehouse_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="inventory_service.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "inventory",
            },
        ),
        migrations.CreateModel(
            name="InventoryHistory",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("addition", "Addition"),
                            ("deduction", "Deduction"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("reservation", "Reservation"),
                            ("release", "Release"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("previous_quantity", models.IntegerField()),
                ("new_quantity", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("performed_by", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        db_column="inventory_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inventory_service.inventory",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inventory"], name="inventory_h_invento_3fc00f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_h_created_c65f00_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["product_id"], name="inventory_product_58b6bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["variant_id"], name="inventory_variant_97c036_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["warehouse"], name="inventory_warehou_c1a64f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product_id", "variant_id", "warehouse")},
        ),
    ]
