# Generated by Django 4.2.13 on 2026-04-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "currency_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("currency_name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("effective_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_currency",
                    models.ForeignKey(
                        db_column="from_currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_from",
                        to="currency_service.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        db_column="to_currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_to",
                        to="currency_service.currency",
                    ),
                ),
            ],
            options={
                "db_table": "exchange_rates",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency"],
                        name="exchange_ra_from_cu_55f9b4_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="exchange_ra_effecti_d78602_idx"
                    ),
                ],
                "unique_together": {("from_currency", "to_currency", "effective_date")},
            },
        ),
    ]
